# Generated by Django 5.2.5 on 2025-08-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post1', '0007_alter_postdb_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdb',
            old_name='users',
            new_name='user',
        ),
    ]
